import {ReactNode} from "react";
import {Metadata} from 'next';
export const metadata: Metadata = {
  title: {
      default: 'Next.js Tutorial - Codevolution',
      template: '%s | Codevolution',
  },
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor: 'lightblue',
          padding: '1rem'
        }}>
            <p>
              Header
            </p>
        </header>
      {children}
        <footer>
            <p>
              Footer
            </p>
        </footer>
      </body>
    </html>
  )
}
